$(Document).ready(function(){
    $('.header__burger').click(function(event){
        $('.header__container,.header__burger-back').addClass('active')
        $('.header__background').addClass('active-back')
        $('body').addClass('lock');
    });
    $('.header__krest').click(function(event){
        $('.header__container,.header__burger-back').removeClass('active')
        $('.header__background').removeClass('active-back')
        $('body').removeClass('lock');
    });
});